edition = "2021"
max_width = 200
hard_tabs = true
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
use_small_heuristics = "Default"
trailing_comma = "Never"
match_block_trailing_comma = false
wrap_comments = true
format_code_in_doc_comments = true
comment_width = 80
normalize_comments = true
format_macro_bodies = true
use_try_shorthand = true
merge_derives = true
use_field_init_shorthand = true
force_explicit_abi = true
