edition = "2021"
max_width = 160
hard_tabs = true
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
use_small_heuristics = "Default"
trailing_comma = "Never"
match_block_trailing_comma = false
wrap_comments = true
normalize_comments = true
