max_width = 160
reorder_imports = true
hard_tabs = true
tab_spaces = 4
use_small_heuristics = "Default"
trailing_comma = "Never"
match_block_trailing_comma = false
edition = "2021"
wrap_comments = true
normalize_comments = true
group_imports = "StdExternalCrate"
reorder_modules = true
newline_style = "Unix"
