[package]
name = "millennium-macros"
version = "1.0.0-rc.2"
authors = [ "pyke.io", "Tauri Programme within The Commons Conservancy" ]
categories = [ "gui", "os", "filesystem", "web-programming" ]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/pykeio/millennium"
description = "Macros for the Millennium crate."
edition = "2021"
rust-version = "1.57"
exclude = [ ".license_template", "CHANGELOG.md", "/target" ]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = [ "full" ] }
heck = "0.4"
millennium-codegen = { path = "../millennium-codegen", default-features = false }
millennium-utils = { path = "../millennium-utils" }

[features]
custom-protocol = [ ]
compression = [ "millennium-codegen/compression" ]
isolation = [ "millennium-codegen/isolation" ]
shell-scope = [ "millennium-codegen/shell-scope" ]
config-json5 = [ "millennium-codegen/config-json5", "millennium-utils/config-json5" ]
