[build]
dist-dir = [ "./index.html" ]
dev-path = [ "./index.html" ]
with-global-millennium = true

[millennium.bundle]
active = true
targets = "all"
identifier = "io.pyke.vibrancy-demo"
icon = [
	"../../.icons/32x32.png",
	"../../.icons/128x128.png",
	"../../.icons/256x256.png",
	"../../.icons/icon.ico"
]

[millennium.allowlist]
all = false

[[millennium.windows]]
title = "Millennium Vibrancy"
width = 600
height = 400
resizable = true
transparent = true
center = true

[millennium.security.csp]
default-src = "millennium: millennium.localhost 'unsafe-inline' 'self'"
