name: Check tools
on:
  push:
    paths:
      - '.github/workflows/check-tools.yml'
      - 'tools/**/*.rs'
      - 'tools/**/Cargo.toml'
      - 'rustfmt.toml'
  pull_request:
    paths:
      - '.github/workflows/check-tools.yml'
      - 'tools/**/*.rs'
      - 'tools/**/Cargo.toml'
      - 'rustfmt.toml'
env:
  RUST_BACKTRACE: 1
  CARGO_PROFILE_DEV_DEBUG: 0 # This would add unnecessary bloat to the target folder, decreasing cache efficiency.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check_fmt:
    name: Check fmt (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  check_clippy:
    name: Run clippy (Rust)
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev webkit2gtk-4.1 libgtksourceview-3.0-dev libayatana-appindicator3-dev librsvg2-dev patchelf
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: tooling/cli
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./tools/Cargo.toml
