name: Lint & Format
on:
  push:
    paths:
      - '.github/workflows/lint-and-format.yml'
      - 'src/**/*.rs'
      - 'rustfmt.toml'
  pull_request:
    paths:
      - '.github/workflows/lint-and-format.yml'
      - 'src/**/*.rs'
      - 'rustfmt.toml'
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0 # This is set to 0 by rust-cache.
  CARGO_PROFILE_DEV_DEBUG: 0 # This would add unnecessary bloat to the target folder, decreasing cache efficiency.
jobs:
  check_fmt:
    name: Check fmt (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  check_clippy:
    name: Run clippy (Rust)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clippy:
          - { args: '', key: 'empty' }
          - { args: '--features compression,millennium_webview,isolation,custom-protocol,api-all,cli,updater,system-tray,http-multipart', key: 'all' }
          - { args: '--no-default-features', key: 'no-default' }
          - { args: '--features custom-protocol', key: 'custom-protocol' }
          - { args: '--features api-all', key: 'api-all' }
    steps:
      - uses: actions/checkout@v2
      - name: Install webkit2gtk
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev patchelf
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Cache Cargo state
        uses: actions/cache@v2
        env:
          cache-name: cargo-state
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ matrix.platform }}-stable-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
          restore-keys: |
            ubuntu-stable-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}-
            ubuntu-stable-${{ env.cache-name }}-
            ubuntu-stable-
            ubuntu-
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets ${{ matrix.clippy.args }}
          name: ${{ matrix.clippy.key }}
