name: Test Millennium
on:
  push:
    paths:
      - '.github/workflows/test-main.yml'
      - 'src/**/*.rs'
      - 'src/**/Cargo.toml'
  pull_request:
    paths:
      - '.github/workflows/test-main.yml'
      - 'src/**/*.rs'
      - 'src/**/Cargo.toml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0 # This is set to 0 by rust-cache.
  CARGO_PROFILE_DEV_DEBUG: 0 # This would add unnecessary bloat to the target folder, decreasing cache efficiency.
jobs:
  test-main:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - {
              target: x86_64-pc-windows-msvc,
              os: windows-latest,
              toolchain: '1.61.0'
            }
          - {
              target: x86_64-unknown-linux-gnu,
              os: ubuntu-latest,
              toolchain: '1.59.0'
            }
          - {
              target: x86_64-apple-darwin,
              os: macos-latest,
              toolchain: '1.59.0'
            }
    steps:
      - uses: actions/checkout@v2
      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.platform.toolchain }}
          target: ${{ matrix.platform.target }}
          override: true
      - name: Install Linux dependencies
        if: contains(matrix.platform.target, 'unknown-linux')
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev patchelf
      - name: Install WebView2
        if: matrix.platform.os == 'windows-latest'
        shell: pwsh
        run: |
          Invoke-WebRequest https://go.microsoft.com/fwlink/p/?LinkId=2124703 -OutFile installwebview.exe -UseBasicParsing
          cmd /C start /wait installwebview.exe /silent /install
      - name: Get current date
        if: matrix.platform.os == 'macos-latest' || matrix.platform.os == 'ubuntu-latest'
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Get current date
        if: matrix.platform.os == 'windows-latest'
        run: echo "CURRENT_DATE=$(Get-Date -Format "yyyy-MM-dd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Cache Cargo state
        uses: actions/cache@v2
        env:
          cache-name: cargo-state
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ matrix.platform.os }}-${{ matrix.platform.toolchain }}-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
          restore-keys: |
            ${{ matrix.platform.os }}-${{ matrix.platform.toolchain }}-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}-
            ${{ matrix.platform.os }}-${{ matrix.platform.toolchain }}-${{ env.cache-name }}-
            ${{ matrix.platform.os }}-${{ matrix.platform.toolchain }}-
            ${{ matrix.platform.os }}-
      - name: Test Rust packages
        run: |
          cargo test --target ${{ matrix.platform.target }} --verbose -p millennium
          cargo test --target ${{ matrix.platform.target }} --verbose -p millennium --features api-all
          cargo test --target ${{ matrix.platform.target }} --verbose -p millennium --features compression,millennium_webview,isolation,custom-protocol,api-all,cli,updater,system-tray,windows7-compat,http-multipart
